import type { Product } from "./types"

export const products: Product[] = [
  // EPI - Équipements de Protection Individuelle
  {
    id: "1",
    titre: "Casque de Sécurité Pro",
    description: "Casque de protection haute résistance avec jugulaire réglable. Conforme EN 397.",
    prix: 45,
    categorie: "EPI",
    image: "/safety-helmet-industrial-yellow.jpg",
  },
  {
    id: "2",
    titre: "Gants Anti-Coupure Niveau 5",
    description: "Gants de protection contre les coupures, niveau 5. Paume renforcée en nitrile.",
    prix: 28,
    categorie: "EPI",
    image: "/cut-resistant-work-gloves-industrial.jpg",
  },
  {
    id: "3",
    titre: "Chaussures de Sécurité S3",
    description: "Chaussures de travail avec coque acier, semelle anti-perforation. Norme S3 SRC.",
    prix: 89,
    categorie: "EPI",
    image: "/safety-work-boots-industrial-black.jpg",
  },
  {
    id: "4",
    titre: "Lunettes de Protection",
    description: "Lunettes anti-projections avec traitement anti-buée. Branches ajustables.",
    prix: 18,
    categorie: "EPI",
    image: "/safety-glasses-protective-eyewear.jpg",
  },
  // SECOURISME
  {
    id: "5",
    titre: "Trousse de Secours Entreprise",
    description: "Kit premiers secours complet pour 20 personnes. Conforme code du travail.",
    prix: 125,
    categorie: "SECOURISME",
    image: "/first-aid-kit-professional-red-cross.jpg",
  },
  {
    id: "6",
    titre: "Défibrillateur Automatique",
    description: "DAE automatique avec instructions vocales. Électrodes adultes et pédiatriques incluses.",
    prix: 1250,
    categorie: "SECOURISME",
    image: "/automatic-defibrillator-aed-medical.jpg",
  },
  {
    id: "7",
    titre: "Brancard Pliant",
    description: "Brancard d'évacuation pliable en aluminium. Capacité 150 kg, sangles incluses.",
    prix: 320,
    categorie: "SECOURISME",
    image: "/folding-stretcher-emergency-evacuation.jpg",
  },
  {
    id: "8",
    titre: "Couverture de Survie",
    description: "Pack de 10 couvertures isothermiques or/argent. Dimensions 210x160 cm.",
    prix: 15,
    categorie: "SECOURISME",
    image: "/emergency-survival-blanket-gold-silver.jpg",
  },
  // SIGNALISATION
  {
    id: "9",
    titre: "Panneau Danger Électrique",
    description: "Panneau signalétique risque électrique. PVC rigide 300x200mm.",
    prix: 12,
    categorie: "SIGNALISATION",
    image: "/electrical-danger-warning-sign-yellow-triangle.jpg",
  },
  {
    id: "10",
    titre: "Cônes de Signalisation (lot 5)",
    description: "Cônes de balisage haute visibilité 50cm. Bandes réfléchissantes.",
    prix: 65,
    categorie: "SIGNALISATION",
    image: "/orange-traffic-cones-safety.jpg",
  },
  {
    id: "11",
    titre: "Ruban de Balisage 500m",
    description: "Ruban de signalisation rouge/blanc. Non adhésif, haute résistance.",
    prix: 25,
    categorie: "SIGNALISATION",
    image: "/red-white-barrier-tape-safety.jpg",
  },
  {
    id: "12",
    titre: "Plan d'Évacuation Luminescent",
    description: "Plan d'évacuation photoluminescent format A3. Cadre aluminium inclus.",
    prix: 85,
    categorie: "SIGNALISATION",
    image: "/emergency-evacuation-plan-green-luminescent.jpg",
  },
  // INDUSTRIEL
  {
    id: "13",
    titre: "Moteur Industriel HD-500",
    description: "Moteur haute performance pour applications industrielles. Puissance 500 CV.",
    prix: 12500,
    categorie: "INDUSTRIEL",
    image: "/industrial-motor-engine-heavy-duty.jpg",
  },
  {
    id: "14",
    titre: "Compresseur Air Pro X200",
    description: "Compresseur d'air professionnel avec réservoir 200L. Usage intensif.",
    prix: 3200,
    categorie: "INDUSTRIEL",
    image: "/industrial-air-compressor-professional.jpg",
  },
  {
    id: "15",
    titre: "Pompe Hydraulique PH-80",
    description: "Pompe hydraulique haute pression. Débit 80 L/min pour systèmes industriels.",
    prix: 4500,
    categorie: "INDUSTRIEL",
    image: "/hydraulic-pump-industrial.jpg",
  },
  {
    id: "16",
    titre: "Générateur Diesel GD-1000",
    description: "Générateur diesel robuste 1000 kVA. Alimentation de secours industrielle.",
    prix: 45000,
    categorie: "INDUSTRIEL",
    image: "/industrial-diesel-generator.jpg",
  },
  // LOGISTIQUE
  {
    id: "17",
    titre: "Chariot Élévateur CE-3000",
    description: "Chariot élévateur électrique capacité 3 tonnes. Batterie longue durée.",
    prix: 32000,
    categorie: "LOGISTIQUE",
    image: "/electric-forklift-warehouse.jpg",
  },
  {
    id: "18",
    titre: "Transpalette Manuel 2500kg",
    description: "Transpalette hydraulique manuel. Fourches 1150mm, roues nylon.",
    prix: 450,
    categorie: "LOGISTIQUE",
    image: "/manual-pallet-jack-warehouse.jpg",
  },
  {
    id: "19",
    titre: "Rayonnage Industriel 4 Niveaux",
    description: "Étagère métallique charge lourde. 2000x600x2000mm, 300kg/niveau.",
    prix: 280,
    categorie: "LOGISTIQUE",
    image: "/industrial-metal-shelving-warehouse.jpg",
  },
  {
    id: "20",
    titre: "Bacs de Stockage (lot 10)",
    description: "Bacs gerbables en plastique renforcé. Dimensions 400x300x200mm.",
    prix: 95,
    categorie: "LOGISTIQUE",
    image: "/placeholder.svg?height=400&width=400",
  },
]

export const categories = ["TOUS", "EPI", "SECOURISME", "SIGNALISATION", "INDUSTRIEL", "LOGISTIQUE"]
